### ISSUE TITLE
你好作者,能否求个联系方式交流一下

### ISSUE THREAD

**Issue by Lingwcy** [chawolbaka/MinecraftProtocol#3]
我正在尝试从客户端发送一个chat message数据包到服务端。wiki.vg上面给的例子有点看不太懂

**Comment by chawolbaka** [comment]
wiki.vg的例子我也看不懂，你是编写mod的吗？
如果需要使用mc自带的ChatComponent我不太熟悉，应该帮不上你。
我这边是参考其它项目加上截取了一些mc发的数据包参考着编写的，如果你觉得可以帮上你可以留个联系方式

**Comment by Lingwcy** [comment]
不是的，没有写mod。我打算写一个简单的bot用来监听QQ群的消息然后打成玩家数据包发送到服务端。
qq群的消息监听用的一个叫mirai的项目。我就只需要把收到的消息打成数据包发给服务端就好了。
我也看过Minecraft console那个开源项目但是那个源码发数据包的源码有点看不懂，就是这个原因。然后我用机器人简单的测试几次，每次一登陆发几串消息就把我踢出去了。一看后台说我发的包数据大小超出预期。
你会经常用QQ交流吗？我留个QQ可以吗？
1444707851
