### ISSUE TITLE
My note

### ISSUE THREAD

**Issue by TomJambeingofamnesiaubermensch** [chawolbaka/MinecraftProtocol#6]
第一性征：内外生殖系统的形成
第二性征：遗精、月经
第三性征：社会性别
性度：男性女性气质的明显度
性感：激发性的欲望的一种特点
性别自我概念：个体形成有关自己的稳定看法，是一种自己知觉
性向：人的行为与性别预先适合性，性别角色和性角色。
没有人是绝对的异性恋和同性恋
新中国的人更多的在同性的情感中活着。
同性恋不等于同性情感
对同性恋的看法可能基于性行为产生的社会稳定性、安全性、疾病、前途命运发展性问题等等。
中国同性很安全不会产生性行为
泛性论：一切为“性”，身体激发的快感当成性欲。人类满足生存需要是为了性。
生命发展的原初动力是性驱力，称为libido
精神结构和心理发展的三个维度。
性驱力发展分期
1儿童口欲期，口欲没有得到满足，口部刺激的快乐会多一些。
2.肛欲期，情绪的释放，控制大小便，体会排便的快乐，控制亲密关系
3.性器期，皮肤刺激，摆弄身体，男生玩弄触碰生殖器，2-3岁女生腿摩擦快感，摩擦癖
4.Oedipus complex
5.潜伏期，对身体不感兴趣，把注意力放在外部，友情社会发展世界
彼此重叠
12岁青春期到来结束
皮肤接触刺激贯穿整个生命
第二个维度—关系发展动力
孩子—父母亲，父母亲的满足
少女年时期—老师，看成自我的客体，影响对我自己的评价、态度
青春期，社会文化与榜样，自我的图式，影响青少女年人生命发展的一大动力，心理被社会养育而来，客体关系的投注造成的趋同，社会自我印象的趋同
第三—Self，自我的力量，自恋自尊自我满足自信，自我长大的一种力量（人人为我，我为人人），老年人“后自恋”。不需要爱、安全、物质，需要尊重，to be self，个性化导致多元化
亲密关系只有两种，有性行为后的关系与无性行为的关系，包括亲情，亲情的亲密关系也是在互相的成长发展之中，“有性行为”是指亲密关系的双方感知到自己正在产生性行为或者单纯服务另一方的或者是强迫的，不论何种方式，必须是双方互动并且感知到自己正在与对方发生性行为。

**Comment by TomJambeingofamnesiaubermensch** [comment]
除了男同性恋以外，希腊罗马的女同性恋也很盛行，成为其他民族史上少有记载的社会现象。雅典流行，斯巴达更盛，但其中心却公认为累斯博斯岛（小亚沿岸）。因此女同性恋叫做“累斯博斯主义”（lesbian），也有按照意思叫做tribalism的。除了累夫卡斯岛（希腊西海岸）的妇女弗拉尼斯，因写出第一本带有描绘女同性恋姿式插图的书而名声大噪外（Reay Tannahill, Sex in History, Scarborough House,London,1981，p88），最著名的女同性恋者，要算累斯博斯岛上的女诗人萨福。

**Comment by TomJambeingofamnesiaubermensch** [comment]
![Screenshot_20230811-112122_Moonlight](https://github.com/chawolbaka/MinecraftProtocol/assets/142173840/17cc59b3-64f9-44d1-911d-158fb18036d9)

**Comment by chawolbaka** [comment]
你好，如果需要记录笔记请自己创建一个repository或使用笔记软件，请不要在别人的项目中提交与项目无关的issue。

**Comment by tomjam23** [comment]
> 你好，如果需要记录笔记请自己创建一个repository或使用笔记软件，请不要在别人的项目中提交与项目无关的issue。

你确实是个傻逼，请问我说你是个傻逼sb or Unsmart Girl你有什么意见吗？
